include: package:lint/analysis_options.yaml

analyzer:
  exclude:
    - lib/**.freezed.dart
    - lib/**.g.dart
  errors:
    missing_required_param: error
    missing_return: error
    must_be_immutable: error
    
linter:
  rules:
    avoid_classes_with_only_static_members: false
    overridden_fields: false
    sort_pub_dependencies: false
